// Top competitor data for /vs/[slug] pages and comparison logic
export const competitors = [
  {
    slug: 'setsmart',
    name: 'SetSmart',
    tagline: 'AI appointment setter for Instagram coaches',
    price: '$99/mo + per-message',
    free: '7-day trial (CC required)',
    channels: ['Instagram', 'WhatsApp', 'Messenger'],
    strengths: ['Polished Meta-API onboarding', 'Established with 500+ coaches', 'Native Calendly + iClosed booking'],
    weaknesses: ['Per-message cost on top of $99/mo (bills scale unpredictably)', 'No way to test the agent before connecting Instagram', '7-day trial requires credit card', 'No web chat / SMS / email channel', 'Closed prompt — limited transparency over what your AI is actually saying'],
    wins: ['Free forever tier with full chat simulator', 'Instant 60-second agent build — zero Meta approval needed to try', 'Flat-rate pricing, no per-message surprises', 'Web widget + SMS + email channels (not just Meta)', 'Open prompt: see and edit exactly what your AI says', 'Every conversation is a public branded share link'],
  },
  { slug: 'manychat', name: 'ManyChat', tagline: 'Chat marketing flow builder', price: '$15-$45/mo', free: 'Free plan (1000 contacts)', channels: ['Instagram','Messenger','WhatsApp','SMS'], strengths: ['Visual flow builder','Massive integration library','Low entry price'], weaknesses: ['Flow-based, not real conversational AI','No native lead qualification','Bots feel scripted'], wins: ['Real generative AI, not flow-tree','Auto-built qualification script in 60s','Reads tone and adapts mid-conversation'] },
  { slug: 'chatfuel', name: 'Chatfuel', tagline: 'Messenger & Instagram bot platform', price: '$23.99/mo+', free: '50 conversations free', channels: ['Instagram','Messenger','WhatsApp'], strengths: ['Long-time player','Enterprise-grade','AI add-on available'], weaknesses: ['Expensive at scale','AI feels bolted-on','Steep learning curve'], wins: ['AI-native from day one','60s setup vs hours of flow building','Branded shareable transcripts'] },
  { slug: 'inflact', name: 'Inflact (formerly Ingramer)', tagline: 'Instagram growth + DM automation', price: '$58/mo+', free: '7-day trial', channels: ['Instagram'], strengths: ['Bundled with growth tools','Auto DM at scale'], weaknesses: ['DM tools risk Instagram TOS violations','Generic templates, no real qualification AI','Instagram-only'], wins: ['Meta-Business-Partner compliant','Smart qualification — not spam','Multi-channel'] },
  { slug: 'instachamp', name: 'InstaChamp by MobileMonkey', tagline: 'Instagram comment-to-DM bot', price: '$19/mo+', free: 'Free tier', channels: ['Instagram'], strengths: ['Cheap','Comment-to-DM is solid'], weaknesses: ['No real AI conversation','Linear keyword triggers only','No booking inside chat'], wins: ['Full conversation handling, not just keyword triggers','In-chat calendar booking','Pre-deploy testing simulator'] },
  { slug: 'tidio', name: 'Tidio', tagline: 'Live chat + chatbot for websites', price: '$29/mo+', free: 'Free plan', channels: ['Website','Messenger','Instagram'], strengths: ['Solid web chat widget','Lyro AI add-on'], weaknesses: ['Lyro charges per AI conversation','Built for ecom support, not coach sales','Weak DM qualification flow'], wins: ['Built for high-ticket coach sales','Flat pricing on AI conversations','Native Calendly booking'] },
  { slug: 'intercom-fin', name: 'Intercom Fin', tagline: 'AI customer service agent', price: '$0.99 per resolution', free: 'No', channels: ['Web','Email','Messenger'], strengths: ['Enterprise-grade','GPT-4 class AI'], weaknesses: ['$0.99/conversation is brutal','Designed for support not sales','No Instagram'], wins: ['Flat pricing','Designed for sales / booking calls','Instagram + WhatsApp native'] },
  { slug: 'respond-io', name: 'Respond.io', tagline: 'Business messaging inbox', price: '$79/mo+', free: '7-day trial', channels: ['Instagram','WhatsApp','Messenger','SMS','TG'], strengths: ['Unified inbox','Many channels','Workflow automation'], weaknesses: ['Workflow-based, not real LLM agent','Steep learning curve','Expensive starter'], wins: ['Real LLM agent (not workflows)','60s setup, no learning curve','Half the price'] },
  { slug: 'kommo', name: 'Kommo (amoCRM)', tagline: 'Messenger-first CRM', price: '$15/user/mo+', free: '14-day trial', channels: ['Instagram','WhatsApp','Messenger'], strengths: ['Real CRM features','Sales pipeline'], weaknesses: ['Per-user pricing scales fast','AI is bolted on','Not focused on qualification'], wins: ['Per-account flat pricing','AI-native','Purpose-built for high-ticket DM qualification'] },
  { slug: 'gohighlevel', name: 'GoHighLevel', tagline: 'All-in-one agency platform', price: '$97/mo+', free: '14-day trial', channels: ['SMS','Email','Voice','IG','Messenger','WhatsApp'], strengths: ['Massive feature set','Whitelabel'], weaknesses: ['Overwhelming for solo coaches','AI bot is basic','Lots of setup time'], wins: ['Setup in 60s, not days','Focused: just DM setting, done right','Better conversational AI'] },
  { slug: 'voiceflow', name: 'Voiceflow', tagline: 'Conversational AI builder', price: '$50/mo+', free: 'Sandbox free', channels: ['Web','Custom'], strengths: ['Powerful builder','Developer-friendly'], weaknesses: ['Requires technical chops','No Instagram-native','You build everything from scratch'], wins: ['Zero-code, zero-build','Instagram + WhatsApp + Messenger native','60s vs days of building'] },
  { slug: 'botpress', name: 'Botpress', tagline: 'Open-source chatbot platform', price: '$0-$495/mo', free: 'Free tier', channels: ['Web','Messenger','WhatsApp'], strengths: ['Open-source','Highly customisable'], weaknesses: ['Needs developer time','No native qualification logic for coaches','Instagram via workarounds'], wins: ['Built for non-technical coaches','Auto-built qualification script','Native Instagram support'] },
]

export function getCompetitor(slug) { return competitors.find(c => c.slug === slug) }
